---

- name: install pkgs
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - prometheus-postfix-exporter

- name: Enable and start service
  ansible.builtin.service:
    name: prometheus-postfix-exporter
    enabled: yes
    state: started









